// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class Constant
{
        public const string achievement_berhasil_menjawab_pertanyaan_ = "CgkI_fbZn90HEAIQBA"; // <GPGSID>
        public const string achievement_menang_game_pertama_kali_ = "CgkI_fbZn90HEAIQBg"; // <GPGSID>
        public const string achievement_oh_tidak__mundur = "CgkI_fbZn90HEAIQBQ"; // <GPGSID>
        public const string achievement_selamat_datang = "CgkI_fbZn90HEAIQAQ"; // <GPGSID>
        public const string achievement_hilangkan_angka = "CgkI_fbZn90HEAIQBw"; // <GPGSID>
        public const string leaderboard_pemain_terbaik = "CgkI_fbZn90HEAIQAg"; // <GPGSID>

}

